### ISSUE TITLE
Editor not working on Firefox  

### ISSUE THREAD

**Issue by Adnan-shamsi** [atharmohammad/Code-N-Collab#10]
![editorOff](https://user-images.githubusercontent.com/61737425/112814317-caffed00-909c-11eb-8541-6e7fa7783b54.PNG)
![editoron](https://user-images.githubusercontent.com/61737425/112814327-cdfadd80-909c-11eb-98fc-ffb07555f1f5.PNG)

**Comment by atharmohammad** [comment]
Replace % to work in Firefox
