### ISSUE TITLE
React Warnings

### ISSUE THREAD

**Issue by atharmohammad** [atharmohammad/Code-N-Collab#105]
Currently we have many warnings not following `===` conventions and key in map or list, all warnings shall be removed

**Comment by yasuomaidana** [comment]
I'd like to try it

**Comment by atharmohammad** [comment]
> I'd like to try it

Sure , go ahead , dont remove warnings due to async in use effect , you can try removing warnings due to use of  (```==``` instead of ```===```) and warnings due to not using a unique key in lists or map , add a unique key there . warnings will occur in your console only when you open a certain page. since we added cors now you have to setup server . ask us anything if you got stuck somewhere

**Comment by yasuomaidana** [comment]
Hi, right now I'm working with === and == warning, which branch should I take as reference?

**Comment by atharmohammad** [comment]
you can pull from master and merge it into your yjs as yjs is development branch so you have to create PR on yjs

**Comment by yasuomaidana** [comment]
Hi, I have a question about the server. I was having a cors error 
![image](https://user-images.githubusercontent.com/32581141/124517981-fc2e3e80-ddaa-11eb-9f04-bde0fd004661.png)
However, it is supposed that I'm running the server locally.
If I get this messages in server, that means that it is working well?
![image](https://user-images.githubusercontent.com/32581141/124518859-3d275280-ddad-11eb-8768-ce697da956aa.png)

**Comment by yasuomaidana** [comment]
Do you have any recommendation about this warning?
![image](https://user-images.githubusercontent.com/32581141/124519130-0dc51580-ddae-11eb-9af5-9a277efc8d34.png)

**Comment by atharmohammad** [comment]
In your index.js replace ```"origin": process.env.CORS_ORIGIN``` with ```"origin":http://localhost:3000/```, it will allow localhost:300 to access the server removing CORS error,
now, 2nd thing is you have to setup your google cloud platform, in that you have to create a client ID , client secret and redirect_uri=http://localhost:3000/homepage/ , here you can see how to do that
https://support.google.com/cloud/answer/6158849?hl=en
then put 
```    
     GOOGLE_CLIENT_ID=<YOUR_GOOGLE_CLIENT_ID>
     GOOGLE_CLIENT_SECRET=<YOUR_GOOGLE_CLIENT_SECRET>
     redirect_URI=http://localhost:3000/homepage/
```
in your environment variables. this will take care of your redirect_URI error.

**Comment by atharmohammad** [comment]
> Do you have any recommendation about this warning?
> ![image](https://user-images.githubusercontent.com/32581141/124519130-0dc51580-ddae-11eb-9af5-9a277efc8d34.png)

ok so , this warning is due to not giving an ```alt``` props to img tags,resolve them by adding ```alt ``` to those img tags that dont have it like this ```<img src={Something} alt="Something" />``` , alt actually tells if image dont get load so alt is present on screen on place of image and shows what image was it or something realated to it in a one or two word

**Comment by yasuomaidana** [comment]
> In your index.js replace `"origin": process.env.CORS_ORIGIN` with `"origin":http://localhost:3000/`, it will allow localhost:300 to access the server removing CORS error,
> now, 2nd thing is you have to setup your google cloud platform, in that you have to create a client ID , client secret and redirect_uri=http://localhost:3000/homepage/ , here you can see how to do that
> https://support.google.com/cloud/answer/6158849?hl=en
> then put
> 
> ```
>      GOOGLE_CLIENT_ID=<YOUR_GOOGLE_CLIENT_ID>
>      GOOGLE_CLIENT_SECRET=<YOUR_GOOGLE_CLIENT_SECRET>
>      redirect_URI=http://localhost:3000/homepage/
> ```
> 
> in your environment variables. this will take care of your redirect_URI error.

Thank you, it worked

**Comment by yasuomaidana** [comment]
I already solved the alt warning

**Comment by yasuomaidana** [comment]
This code, belongs to `src/Components/Lockout/FilterContest/FilterContest.js`. It has padding defined twice, which should I keep?
``` 
            padding: "10px",
            width: "140px",
            alignText: "center",
            padding: "auto",
```

**Comment by atharmohammad** [comment]
> ## Duplicate error
> These error have some parameters defined twice, which should I keep?
> 
> ## Warning `Line 116:13:  Duplicate key 'padding' `
> path: `src/Components/Lockout/FilterContest/FilterContest.js`
> ``` 
>             padding: "10px",
>             width: "140px",
>             alignText: "center",
>             padding: "auto",
> ```
Take padding : auto  but also comment there ```//duplicate_error``` so that we can find it and check on it also if you find some other warning due to some similar case , leave it as it is and write same comment there for us to find and check it

**Comment by yasuomaidana** [comment]
Hi, did you already check if the main is compiling code? 
I tried to remove some warning issues, then I compiled a python program and got this... I also returned until the point where I remove the duplicated warning and I got the same error.
![image](https://user-images.githubusercontent.com/32581141/124688091-cfa61f80-de9b-11eb-821a-0462d3250a93.png)

**Comment by yasuomaidana** [comment]
In this branch https://github.com/yasuomaidana/Code-N-Collab/tree/remove_warnings I removed all duplicated fields
