### ISSUE TITLE
On click create blog button for non login user, should not be redirected to home page 

### ISSUE THREAD

**Issue by Adnan-shamsi** [atharmohammad/Code-N-Collab#140]
Non login user when click create blog button they should remain on the same page, because we have a login option on  that page too .
![Capture](https://user-images.githubusercontent.com/61737425/125657174-8218be36-67e7-4abc-b68a-c917ae1172cb.PNG)

**Comment by shreyas1925** [comment]
Can I solve this

**Comment by atharmohammad** [comment]
> Can I solve this

sure go ahead ! make PR on develop
