### ISSUE TITLE
Room name bug

### ISSUE THREAD

**Issue by Adnan-shamsi** [atharmohammad/Code-N-Collab#154]
Upper case and Lower case room name are treated as seperate room in yjs
So make sure to pass room name after converting it to LowerCase

Before passing room name to the 
[https://github.com/atharmohammad/Code-N-Collab/blob/master/src/Components/Editor/Editor.js](https://github.com/atharmohammad/Code-N-Collab/blob/master/src/Components/Editor/Editor.js) 

```
provider = new WebrtcProvider(searchParams.get("room").trim(), ydoc, {
          signaling: [
            "wss://signaling.yjs.dev",
            process.env.REACT_APP_SIGNALLING_URL1,
            process.env.REACT_APP_SIGNALLING_URL2,
          ],
          password: location.state ? location.state.password : null,
        });
```
add ``` .toLowerCase() ``` at the end of  ``` searchParams.get("room").trim() ```

**Comment by Sergih28** [comment]
Hi! 👋
I'd like to get involved on this issue.

As far as I understand, the problem is that the room names are **case sensitive**, and you want them to be **case insensitive.**

And to fix it we just need to add ```.toLowerCase()```at the end of ```searchParams.get("room").trim()```

Am I correct?

**Comment by Adnan-shamsi** [comment]
Ye

> Hi! 👋
> I'd like to get involved on this issue.
> 
> As far as I understand, the problem is that the room names are **case sensitive**, and you want them to be **case insensitive.**
> 
> And to fix it we just need to add `.toLowerCase()`at the end of `searchParams.get("room").trim()`
> 
> Am I correct?

Yess
