### ISSUE TITLE
Change Label

### ISSUE THREAD

**Issue by Adnan-shamsi** [atharmohammad/Code-N-Collab#158]
https://github.com/atharmohammad/Code-N-Collab/blob/c7891023f767cf57309867f8f5f8ed824a022fe4/src/Components/Rooms/Rooms.js#L86

replace ` * Choose a Unique Name ` text with ` * What you want to be called ?`

**Comment by soham4abc** [comment]
I am willing to contribute in this issue!

**Comment by atharmohammad** [comment]
> I am willing to contribute in this issue!

Go ahead! But please make sure to make PR on develop branch
