### ISSUE TITLE
Error in inner files of Monaco Editor

### ISSUE THREAD

**Issue by atharmohammad** [atharmohammad/Code-N-Collab#17]
![simple worker](https://user-images.githubusercontent.com/56029409/113972635-8fadad00-9858-11eb-9377-f04366fc1453.PNG)

- After loading the editor page on concole window uncaught promise error is appearing in language feature.js (some inner file in node modules/monaco-editor)

**Comment by atharmohammad** [comment]
UPDATE ON ISSUE

Error is due to javascript not supporteed fully by @monaco-editor/react , Due to this real-time collaboration will be slow and binding will not occur correctly

**Comment by Adnan-shamsi** [comment]
Replaced monaco with CodeMirror
