### ISSUE TITLE
Cursive Writing in Home Page button is not looking great in Mobile version

### ISSUE THREAD

**Issue by Adnan-shamsi** [atharmohammad/Code-N-Collab#99]
**Describe the solution you'd like**
Change it to other suitable font font mobile version

ScreenShot 
![WhatsApp Image 2021-06-24 at 7 40 32 PM](https://user-images.githubusercontent.com/61737425/123277923-29196080-d524-11eb-8cf3-f89b692606ef.jpeg)

**Comment by atharmohammad** [comment]
Issue Resolved in latest yjs commit
